import time
import datetime
import sys
import getpass
import warnings
import os
import numpy
import pyfits

from artemishsc import *


EXPOSURE_TIME = 1.0
DEFAULT_DEVICE = -1
FITS_FILENAME = 'titan.fits'
DTYPE_PIXEL = numpy.uint16
DIVIDER = '-' * 40


def formatted_file_size_kilobytes(input_file):
    size_in_bytes = os.path.getsize(input_file)
    size_in_kilobytes = int(size_in_bytes / 1024)
    formatted_string = format(size_in_kilobytes, ',d') + ' KB'
    return formatted_string


dll_loaded = ArtemisLoadDLL('shared\ArtemisHSC.dll')
print 'DLL loaded: ', dll_loaded
if not dll_loaded:
    sys.exit(1)
print
print

titan = ArtemisConnect(DEFAULT_DEVICE)

print 'General Properties'
print DIVIDER
print 'Artemis API Version: ', ArtemisAPIVersion()
# print 'Device Name: ', ArtemisDeviceName(DEFAULT_DEVICE)
# print 'Device Serial Number: ', ArtemisDeviceSerial(DEFAULT_DEVICE)
print

_, colour_type, normal_offset_x, normal_offset_y, preview_offset_x, preview_offset_y = ArtemisColourProperties(titan)
print "Colour Properties"
print DIVIDER
print 'Colour Type: ', colour_type
print 'Normal Offset X: ', normal_offset_x
print 'Normal Offset Y: ', normal_offset_y
print 'Preview Offset X: ', preview_offset_x
print 'Preview Offset Y: ', preview_offset_y
print

print 'Exposure'
print DIVIDER

# print 'Bin Data: ', ArtemisGetBin(titan)

connected = ArtemisIsConnected(titan)
print 'Connected: ', connected
if not connected:
    raise Exception('device is not connected')

camera_properties = ArtemisProperties_pythonDictionary(titan)
print camera_properties

print 'Starting exposure'
ArtemisStartExposure(titan, EXPOSURE_TIME)

while not ArtemisImageReady(titan):
    time.sleep(0.5)

now = datetime.date.today()
observation_timestamp = datetime.datetime.fromtimestamp(time.time()).isoformat()
print 'Exposure complete'

percent_done = 0
print 'Download % completed: ', percent_done
while percent_done < 100:
    percent_done = ArtemisDownloadPercent(titan)
    print 'Download % completed: ', percent_done

_, x, y, w, h, bin_x, bin_y = ArtemisGetImageData(titan)
print 'Fetched imaged data - x=%d/y=%d w=%d/h=%d bin: x=%d/y=%d' % (x, y, w, h, bin_x, bin_y)
print

print 'FITS File Generation'
print DIVIDER
image_buffer = ArtemisImageBuffer_pythonList(titan)
image_array = numpy.rot90(numpy.asarray(numpy.reshape(image_buffer, (w, h)), dtype=DTYPE_PIXEL, order='C'))

user = getpass.getuser()

header_primary = pyfits.Header()
header_primary['SIMPLE'] = 'T'
header_primary['BITPIX'] = 16
header_primary['BYTEORDR'] = 'BIG_ENDIAN'
header_primary['NAXIS'] = 2
header_primary['NAXIS1'] = h
header_primary['NAXIS2'] = w
header_primary['EXTEND'] = 'T'
header_primary['DATATYPE'] = 'INTEGER*2'
header_primary['DATATYPE'] = 'INTEGER*2'
header_primary['TELESCOP'] = 'N/A'
header_primary['INSTRUME'] = 'Atik Titan'
header_primary['OBJECT'] = 'N/A'
header_primary['OBJECT2'] = '_'
header_primary['ORIGIN'] = 'Las Cumbres Observatory'
header_primary['FEXPTIME'] = int(EXPOSURE_TIME * 1000)
header_primary['DATE'] = observation_timestamp
header_primary['DATE-OBS'] = observation_timestamp
header_primary['BSCALE'] = 1
header_primary['BUNIT'] = 'DN'
header_primary['BZERO'] = 0.0
header_primary['EXPTIME'] = int(EXPOSURE_TIME * 1000)
header_primary['CRPIX1'] = 100.0
header_primary['CRPIX2'] = 100.0
header_primary['CRVAL1'] = 0.0
header_primary['CRVAL2'] = 0.0
header_primary['CRTYPE1'] = 'RA--TAN'
header_primary['CRTYPE2'] = 'DEC--TAN'
header_primary['PSCALE1'] = 1.0
header_primary['PSCALE2'] = 1.0
header_primary['ASTRPROG'] = __file__
header_primary['ASTRVER'] = '1.0'
header_primary['AUTHOR'] = user
header_primary['OBSERVER'] = user

header_primary.add_comment(format('Generated by %s' % ( __file__)))

hdu_primary = pyfits.PrimaryHDU(header=header_primary, data=image_array, uint=True)

print 'Headers:'
for key, value in header_primary.iteritems():
    print '\t%-8s: %s' % (key, value)
print

with warnings.catch_warnings([UserWarning]):
    hdu_primary.writeto(name=FITS_FILENAME, clobber=True, output_verify='fix', checksum=False)

print 'File Size: ', formatted_file_size_kilobytes(FITS_FILENAME)
print

hdu_list = pyfits.open(FITS_FILENAME)
try:
    hdu_list.info()
finally:
    hdu_list.close()

print DIVIDER
print 'Done.'
